/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mhzhou' at '17-6-13 上午10:25' with Gradle 2.14.1
 *
 * @author mhzhou, @date 17-6-13 上午10:25
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
